// The dock's look, as inline styles (the package ships no CSS): the Studio's own dark palette.
import type {CSSProperties} from 'react';

export const colors = {
  background: '#1e1e1e',
  panel: '#252526',
  raised: '#2d2d2d',
  text: '#e6e6e6',
  muted: '#9a9a9a',
  accent: '#0b84f3',
  border: '#333',
  danger: '#e5484d',
  warning: '#e0a020',
  ok: '#3fb950',
} as const;

export const FONT = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif';

export const DOCK_WIDTH = 380;
export const COLLAPSED_WIDTH = 28;
/** The height of the Studio's top bar: the dock starts under it so the Render button stays reachable. */
export const STUDIO_TOP_BAR = 40;

const base: CSSProperties = {
  boxSizing: 'border-box',
  fontFamily: FONT,
  fontSize: 12,
  lineHeight: 1.45,
  color: colors.text,
};

export const styles = {
  /** The dock on one edge, under the top bar; collapsed it is a thin strip so the Props sidebar stays usable. */
  dock: (collapsed: boolean, side: 'left' | 'right'): CSSProperties => ({
    ...base,
    position: 'fixed',
    top: STUDIO_TOP_BAR,
    [side]: 0,
    bottom: 0,
    width: collapsed ? COLLAPSED_WIDTH : DOCK_WIDTH,
    display: 'flex',
    flexDirection: 'column',
    background: colors.background,
    [side === 'right' ? 'borderLeft' : 'borderRight']: `1px solid ${colors.border}`,
    zIndex: 1000,
    overflow: 'hidden',
  }),
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '6px 10px',
    borderBottom: `1px solid ${colors.border}`,
    background: colors.panel,
    flex: '0 0 auto',
  } as CSSProperties,
  title: {fontWeight: 600, fontSize: 13} as CSSProperties,
  collapsedTitle: {
    ...base,
    writingMode: 'vertical-rl',
    transform: 'rotate(180deg)',
    padding: '10px 4px',
    color: colors.muted,
    cursor: 'pointer',
    userSelect: 'none',
    flex: '1 1 auto',
    textAlign: 'center',
  } as CSSProperties,
  tabs: {
    display: 'flex',
    borderBottom: `1px solid ${colors.border}`,
    background: colors.panel,
    flex: '0 0 auto',
  } as CSSProperties,
  tab: (active: boolean): CSSProperties => ({
    ...base,
    flex: '1 1 0',
    padding: '7px 0',
    textAlign: 'center',
    background: 'transparent',
    border: 'none',
    borderBottom: `2px solid ${active ? colors.accent : 'transparent'}`,
    color: active ? colors.text : colors.muted,
    cursor: 'pointer',
    fontWeight: active ? 600 : 400,
  }),
  content: {flex: '1 1 auto', overflowY: 'auto', padding: '10px 12px'} as CSSProperties,
  status: {
    flex: '0 0 auto',
    borderTop: `1px solid ${colors.border}`,
    background: colors.panel,
    padding: '6px 10px',
    minHeight: 30,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  } as CSSProperties,
  statusLine: (tone: 'busy' | 'error' | 'notice' | 'idle'): CSSProperties => ({
    display: 'flex',
    alignItems: 'flex-start',
    gap: 6,
    color: tone === 'error' ? colors.danger : tone === 'notice' ? colors.warning : colors.muted,
    wordBreak: 'break-word',
  }),
  section: {marginBottom: 14} as CSSProperties,
  sectionTitle: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: colors.muted,
    margin: '0 0 6px',
  } as CSSProperties,
  field: {display: 'flex', flexDirection: 'column', gap: 3, marginBottom: 8} as CSSProperties,
  label: {color: colors.muted, fontSize: 11} as CSSProperties,
  row: {display: 'flex', gap: 6, alignItems: 'center', flexWrap: 'wrap'} as CSSProperties,
  input: {
    ...base,
    background: colors.raised,
    border: `1px solid ${colors.border}`,
    borderRadius: 3,
    color: colors.text,
    padding: '4px 6px',
    minWidth: 0,
    width: '100%',
  } as CSSProperties,
  numberInput: {
    ...base,
    background: colors.raised,
    border: `1px solid ${colors.border}`,
    borderRadius: 3,
    color: colors.text,
    padding: '3px 4px',
    width: 72,
  } as CSSProperties,
  button: (variant: 'primary' | 'default' | 'ghost', disabled: boolean): CSSProperties => ({
    ...base,
    padding: variant === 'ghost' ? '1px 5px' : '5px 10px',
    borderRadius: 3,
    border: variant === 'primary' ? 'none' : `1px solid ${colors.border}`,
    background: variant === 'primary' ? colors.accent : variant === 'ghost' ? 'transparent' : colors.raised,
    color: variant === 'primary' ? '#fff' : colors.text,
    cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled ? 0.5 : 1,
    whiteSpace: 'nowrap',
  }),
  note: {color: colors.muted, fontSize: 11, margin: '4px 0 8px'} as CSSProperties,
  list: {listStyle: 'none', margin: 0, padding: 0} as CSSProperties,
  listRow: (active: boolean): CSSProperties => ({
    borderBottom: `1px solid ${colors.border}`,
    padding: '6px 4px',
    cursor: 'pointer',
    background: active ? colors.raised : 'transparent',
  }),
  rtl: {direction: 'rtl', unicodeBidi: 'isolate', fontSize: 15, lineHeight: 1.8, textAlign: 'right'} as CSSProperties,
  bar: {height: 4, background: colors.raised, borderRadius: 2, overflow: 'hidden', flex: '1 1 auto'} as CSSProperties,
  barFill: (ratio: number, color: string): CSSProperties => ({
    height: '100%',
    width: `${Math.round(Math.max(0, Math.min(1, ratio)) * 100)}%`,
    background: color,
  }),
  chip: (kept: boolean, clickable: boolean, marker: boolean): CSSProperties => ({
    ...base,
    fontSize: marker ? 11 : 14,
    direction: 'rtl',
    padding: '1px 6px',
    margin: 2,
    borderRadius: 10,
    border: `1px solid ${colors.border}`,
    background: kept ? colors.raised : 'transparent',
    color: kept ? colors.text : colors.muted,
    opacity: kept ? 1 : 0.5,
    cursor: clickable ? 'pointer' : 'default',
  }),
  splitMarker: {color: colors.accent, fontWeight: 700, margin: '0 2px', alignSelf: 'center'} as CSSProperties,
  flag: (color: string): CSSProperties => ({
    display: 'inline-block',
    padding: '0 5px',
    marginInlineEnd: 4,
    borderRadius: 8,
    fontSize: 10,
    background: color,
    color: '#111',
  }),
  lookGrid: {display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8} as CSSProperties,
  lookCard: (active: boolean, disabled: boolean): CSSProperties => ({
    ...base,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 5,
    textAlign: 'start',
    padding: '8px 9px',
    borderRadius: 4,
    border: `1px solid ${active ? colors.accent : colors.border}`,
    boxShadow: active ? `inset 0 0 0 1px ${colors.accent}` : 'none',
    background: colors.raised,
    cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled ? 0.6 : 1,
  }),
  lookName: {display: 'flex', justifyContent: 'space-between', gap: 4, fontWeight: 600} as CSSProperties,
  lookDescription: {color: colors.muted, fontSize: 11} as CSSProperties,
  swatch: (color: string): CSSProperties => ({
    display: 'inline-block',
    width: 16,
    height: 16,
    borderRadius: 3,
    border: `1px solid ${colors.border}`,
    background: color,
  }),
  code: {fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: 11} as CSSProperties,
};

/** Green for a sure segment, amber for one under 0.9, red under the threshold. */
export const confidenceColor = (confidence: number, threshold: number): string =>
  confidence >= 0.9 ? colors.ok : confidence >= threshold ? colors.warning : colors.danger;
