// Generated by scripts/fonts-package.mjs from manifest.json; do not edit.
/**
 * QUL's KFGQPC V4 qpc-v4 page fonts as URLs your bundler serves. Pass it to
 * @tlawat/remotion-mushaf-line: `<MushafLine fontFallback={fonts} />` (used when QUL's CDN
 * fails) or `fontSrc={fonts}` (the only source). Importing it puts the files in your bundle.
 */
declare const fonts: {
  readonly kind: 'remotion-mushaf-fonts';
  readonly schema: 1;
  readonly name: '@tlawat/mushaf-fonts-qpc-v4';
  readonly version: string;
  readonly mushaf: 'qpc-v4';
  readonly fontSet: 'qpc-v4';
  /** The date of QUL's fonts this version holds (YYYY-MM-DD). */
  readonly snapshot: string;
  /** By page (1-604): the URL the bundler gave the file, its size and its SHA-256 (hex). */
  readonly files: Readonly<Record<number, {readonly url: string; readonly bytes: number; readonly sha256: string}>>;
};
export default fonts;
