#!/usr/bin/env node
// Builds and checks the two fonts packages, packages/fonts-<set>/ (remotion-mushaf-fonts-<set>):
// QUL's KFGQPC V4 page fonts, unmodified, published on npm so a render can fall back to them when
// QUL's CDN fails. Zero dependencies; Node >= 20. Run it as `bun run fonts-packages <command>` or
// `node scripts/fonts-package.mjs <command>`.
//
// What is committed: manifest.json (every file's name, size, MD5 and SHA-256), the generated
// index.js / index.d.ts, the licence and the notes. What is not: fonts/, the files themselves,
// filled before a test run or a publish from the example's mirror, a previous version or the CDN,
// and checked against the manifest byte for byte.
//
//   fonts snapshot <set> --from <dir> [--date YYYY-MM-DD]
//                           Record the files in <dir> (p<page>.woff2, or .woff where QUL has no
//                           woff2) as the package's new snapshot: rewrites manifest.json, sets the
//                           version to 1.<YYYYMMDD>.0 when a file changed, regenerates index.js and
//                           index.d.ts and prepends a CHANGELOG entry listing the changed pages.
//   fonts generate <set>    Rewrite index.js and index.d.ts from manifest.json and package.json.
//   fonts fill <set|all> [--from <dir>] [--cdn]
//                           Put the snapshot's files in fonts/: from <dir> (default: the example's
//                           mirror, example/public/fonts/<set>), then, with --cdn, from QUL's CDN.
//                           Files already in place and correct are kept.
//   fonts verify <set|all>  fonts/ holds exactly the manifest's files, with its sizes and hashes.
//   fonts check <set|all> [--metadata]
//                           The generated entry matches the manifest, and `npm pack` would publish
//                           exactly the declared files (with --metadata: everything but fonts/).
//   fonts drift <set|all> [--json]
//                           Compare the snapshot with QUL's CDN (HEAD, ETag = MD5); exit 1 on drift.
//   fonts download <set> --out <dir> [--pages <list>]
//                           Download the current files from QUL's CDN into <dir> (for a new snapshot).

import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fetchWithRetry, parsePageList, ROOT, runPool} from './lib/cli.mjs';
import {QPC_V4} from './lib/datasets.mjs';
import {detectFontMagic} from './lib/sfnt.mjs';

export const SETS = ['qpc-v4', 'qpc-v4-tajweed'];
const PAGES = QPC_V4.pages;

export const packageDir = (set) => path.join(ROOT, 'packages', `fonts-${set}`);
const manifestPath = (set) => path.join(packageDir(set), 'manifest.json');
const fontsDir = (set) => path.join(packageDir(set), 'fonts');
const mirrorDir = (set) => path.join(ROOT, 'example/public/fonts', set);

const log = (...a) => console.log('[fonts]', ...a);
const fail = (message) => {
  console.error(`[fonts] ${message}`);
  process.exit(1);
};

const hash = (algorithm, bytes) => createHash(algorithm).update(bytes).digest('hex');
const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));
const writeJson = (file, value) => fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);

const assertSet = (set) => {
  if (!SETS.includes(set)) fail(`unknown font set ${JSON.stringify(set)} (expected ${SETS.join(' or ')})`);
  return set;
};
const setsOf = (arg) => (arg === 'all' ? SETS : [assertSet(arg)]);

export const readManifest = (set) => readJson(manifestPath(set));
const readPackageJson = (set) => readJson(path.join(packageDir(set), 'package.json'));

/** The file of a page in a directory of page fonts: its woff2, else its woff (QUL's gaps). */
const findPageFile = (dir, page) => {
  for (const format of ['woff2', 'woff']) {
    const file = path.join(dir, `p${page}.${format}`);
    if (fs.existsSync(file)) return file;
  }
  return null;
};

/** QUL's CDN URL of a file of the snapshot (the manifest names its format). */
export const cdnUrlOf = (set, fileName) => {
  const format = path.extname(fileName).slice(1);
  const page = Number(fileName.match(/^p(\d+)\./)[1]);
  return QPC_V4.fontUrl(set, page, format);
};

const describeFile = (bytes) => ({bytes: bytes.length, md5: hash('md5', bytes), sha256: hash('sha256', bytes)});

// ---- generate ----------------------------------------------------------------------------------

/** index.js: one `new URL(<file>, import.meta.url)` per page, the form bundlers turn into an asset. */
export const renderIndexJs = (manifest, version) => {
  const lines = [
    '// Generated by scripts/fonts-package.mjs from manifest.json; do not edit.',
    '// Each `new URL(<file>, import.meta.url)` is what makes a bundler (webpack, Rspack, Vite) emit the',
    '// file as an asset and hand back its URL; nothing is downloaded until a line needs the page.',
    'const file = (url, bytes, sha256) => ({url: url.href, bytes, sha256});',
    '',
    'export default {',
    "  kind: 'remotion-mushaf-fonts',",
    '  schema: 1,',
    `  name: '${manifest.name}',`,
    `  version: '${version}',`,
    `  mushaf: '${manifest.mushaf}',`,
    `  fontSet: '${manifest.fontSet}',`,
    `  snapshot: '${manifest.snapshot}',`,
    '  files: {',
  ];
  for (const [page, f] of Object.entries(manifest.files).sort((a, b) => Number(a[0]) - Number(b[0]))) {
    lines.push(`    ${page}: file(new URL('./fonts/${f.file}', import.meta.url), ${f.bytes}, '${f.sha256}'),`);
  }
  lines.push('  },', '};', '');
  return lines.join('\n');
};

export const renderIndexDts = (manifest) =>
  [
    '// Generated by scripts/fonts-package.mjs from manifest.json; do not edit.',
    '/**',
    ` * QUL's KFGQPC V4 ${manifest.fontSet} page fonts as URLs your bundler serves. Pass it to`,
    " * remotion-mushaf-line-renderer: `<MushafLine fontFallback={fonts} />` (used when QUL's CDN",
    ' * fails) or `fontSrc={fonts}` (the only source). Importing it puts the files in your bundle.',
    ' */',
    'declare const fonts: {',
    "  readonly kind: 'remotion-mushaf-fonts';",
    '  readonly schema: 1;',
    `  readonly name: '${manifest.name}';`,
    '  readonly version: string;',
    `  readonly mushaf: '${manifest.mushaf}';`,
    `  readonly fontSet: '${manifest.fontSet}';`,
    "  /** The date of QUL's fonts this version holds (YYYY-MM-DD). */",
    '  readonly snapshot: string;',
    '  /** By page (1-604): the URL the bundler gave the file, its size and its SHA-256 (hex). */',
    '  readonly files: Readonly<Record<number, {readonly url: string; readonly bytes: number; readonly sha256: string}>>;',
    '};',
    'export default fonts;',
    '',
  ].join('\n');

const generate = (set) => {
  const manifest = readManifest(set);
  const {version} = readPackageJson(set);
  fs.writeFileSync(path.join(packageDir(set), 'index.js'), renderIndexJs(manifest, version));
  fs.writeFileSync(path.join(packageDir(set), 'index.d.ts'), renderIndexDts(manifest));
  log(`${set}: wrote index.js and index.d.ts (${Object.keys(manifest.files).length} pages, ${version})`);
};

// ---- snapshot ----------------------------------------------------------------------------------

const snapshot = (set, from, date) => {
  if (!from) fail('snapshot needs --from <dir>');
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) fail(`--date must be YYYY-MM-DD, got ${JSON.stringify(date)}`);
  const previous = fs.existsSync(manifestPath(set)) ? readManifest(set) : null;
  const files = {};
  const missing = [];
  for (let page = 1; page <= PAGES; page++) {
    const file = findPageFile(from, page);
    if (!file) {
      missing.push(page);
      continue;
    }
    const bytes = fs.readFileSync(file);
    const format = detectFontMagic(bytes);
    if (format !== path.extname(file).slice(1))
      fail(`${file} is not a ${path.extname(file).slice(1)} file (${format})`);
    files[page] = {file: path.basename(file), ...describeFile(bytes)};
  }
  if (missing.length) fail(`${from} lacks ${missing.length} page(s): ${missing.slice(0, 20).join(', ')}`);
  const changed = Object.keys(files).filter((p) => previous?.files[p]?.sha256 !== files[p].sha256);
  const manifest = {
    kind: 'remotion-mushaf-fonts/manifest',
    schema: 1,
    name: `remotion-mushaf-fonts-${set}`,
    mushaf: 'qpc-v4',
    fontSet: set,
    snapshot: changed.length || !previous ? date : previous.snapshot,
    source: `${QPC_V4.fontUrl(set, 1, 'woff2').replace(/\/woff2\/p1\.woff2.*$/, '')}/{woff2,woff}/p<page>.<format>`,
    totalBytes: Object.values(files).reduce((sum, f) => sum + f.bytes, 0),
    files,
  };
  writeJson(manifestPath(set), manifest);
  const pkgFile = path.join(packageDir(set), 'package.json');
  const pkg = readJson(pkgFile);
  if (changed.length && previous) {
    pkg.version = `1.${date.replaceAll('-', '')}.0`;
    writeJson(pkgFile, pkg);
    const changelog = path.join(packageDir(set), 'CHANGELOG.md');
    const body = fs.existsSync(changelog) ? fs.readFileSync(changelog, 'utf8') : '# Changelog\n';
    const entry = `## ${pkg.version}\n\nQUL's fonts as of ${date}. Changed pages (${changed.length}): ${changed.join(', ')}.\n`;
    fs.writeFileSync(changelog, body.replace(/^# Changelog\n/, `# Changelog\n\n${entry}`));
  }
  generate(set);
  log(
    `${set}: snapshot ${manifest.snapshot}, ${Object.keys(files).length} files, ${(manifest.totalBytes / 1e6).toFixed(1)} MB; ${previous ? `${changed.length} page(s) changed` : 'first snapshot'}`,
  );
};

// ---- fill / verify -----------------------------------------------------------------------------

const matches = (file, entry) => {
  if (!fs.existsSync(file)) return false;
  const bytes = fs.readFileSync(file);
  return bytes.length === entry.bytes && hash('sha256', bytes) === entry.sha256;
};

const fill = async (set, {from, cdn}) => {
  const manifest = readManifest(set);
  const source = from ?? mirrorDir(set);
  fs.mkdirSync(fontsDir(set), {recursive: true});
  let kept = 0;
  let copied = 0;
  const needed = [];
  for (const entry of Object.values(manifest.files)) {
    const target = path.join(fontsDir(set), entry.file);
    if (matches(target, entry)) {
      kept++;
      continue;
    }
    const candidate = path.join(source, entry.file);
    if (fs.existsSync(candidate)) {
      const bytes = fs.readFileSync(candidate);
      if (bytes.length === entry.bytes && hash('sha256', bytes) === entry.sha256) {
        fs.writeFileSync(target, bytes);
        copied++;
        continue;
      }
      log(`${set}: ${path.relative(ROOT, candidate)} differs from the snapshot; not used`);
    }
    needed.push(entry);
  }
  let downloaded = 0;
  if (needed.length && cdn) {
    await runPool(needed, 4, async (entry) => {
      const url = cdnUrlOf(set, entry.file);
      const res = await fetchWithRetry(url, {accept: '*/*'});
      const bytes = Buffer.from(await res.arrayBuffer());
      if (bytes.length !== entry.bytes || hash('sha256', bytes) !== entry.sha256) {
        throw new Error(
          `${url} is no longer the snapshot's file (QUL rebuilt it): run \`fonts drift ${set}\` and take a new snapshot`,
        );
      }
      fs.writeFileSync(path.join(fontsDir(set), entry.file), bytes);
      downloaded++;
    });
  }
  const left = needed.length - downloaded;
  log(`${set}: ${kept} in place, ${copied} copied from ${path.relative(ROOT, source)}, ${downloaded} downloaded`);
  if (left > 0)
    fail(
      `${set}: ${left} file(s) missing (${needed
        .map((e) => e.file)
        .slice(0, 10)
        .join(', ')}…); pass --from <dir> or --cdn`,
    );
};

export const verify = (set, {quiet = false} = {}) => {
  const manifest = readManifest(set);
  const problems = [];
  const expected = new Set(Object.values(manifest.files).map((e) => e.file));
  if (Object.keys(manifest.files).length !== PAGES)
    problems.push(`the manifest lists ${Object.keys(manifest.files).length} pages, not ${PAGES}`);
  const present = fs.existsSync(fontsDir(set)) ? fs.readdirSync(fontsDir(set)) : [];
  for (const name of present) if (!expected.has(name)) problems.push(`fonts/${name} is not in the manifest`);
  for (const [page, entry] of Object.entries(manifest.files)) {
    const file = path.join(fontsDir(set), entry.file);
    if (!fs.existsSync(file)) {
      problems.push(`fonts/${entry.file} (page ${page}) is missing`);
      continue;
    }
    const bytes = fs.readFileSync(file);
    const d = describeFile(bytes);
    if (d.bytes !== entry.bytes || d.md5 !== entry.md5 || d.sha256 !== entry.sha256)
      problems.push(`fonts/${entry.file} differs from the manifest`);
    if (detectFontMagic(bytes) !== path.extname(entry.file).slice(1))
      problems.push(`fonts/${entry.file} is not a ${path.extname(entry.file)} file`);
  }
  if (problems.length) {
    for (const p of problems.slice(0, 30)) console.error(`[fonts] ${set}: ${p}`);
    fail(`${set}: ${problems.length} problem(s); run \`fonts fill ${set}\``);
  }
  if (!quiet) log(`${set}: ${present.length} files match the manifest (snapshot ${manifest.snapshot})`);
};

// ---- check -------------------------------------------------------------------------------------

const METADATA_FILES = [
  'CHANGELOG.md',
  'LICENSE.md',
  'NOTICE.md',
  'README.md',
  'index.d.ts',
  'index.js',
  'manifest.json',
  'package.json',
];

const check = (set, {metadata}) => {
  const dir = packageDir(set);
  const manifest = readManifest(set);
  const pkg = readPackageJson(set);
  const problems = [];
  if (pkg.name !== manifest.name) problems.push(`package.json name ${pkg.name} ≠ manifest name ${manifest.name}`);
  if (!/^1\.\d{8}\.\d+$/.test(pkg.version)) problems.push(`version ${pkg.version} is not 1.<YYYYMMDD>.<patch>`);
  if (pkg.version.split('.')[1] !== manifest.snapshot.replaceAll('-', ''))
    problems.push(`version ${pkg.version} does not carry the snapshot date ${manifest.snapshot}`);
  if (fs.readFileSync(path.join(dir, 'index.js'), 'utf8') !== renderIndexJs(manifest, pkg.version))
    problems.push(`index.js is out of date: run \`fonts generate ${set}\``);
  if (fs.readFileSync(path.join(dir, 'index.d.ts'), 'utf8') !== renderIndexDts(manifest))
    problems.push(`index.d.ts is out of date: run \`fonts generate ${set}\``);
  if (!metadata) verify(set, {quiet: true});
  // npm's own view of the tarball (scripts off: prepack would verify fonts/ again).
  const out = execFileSync('npm', ['pack', '--dry-run', '--json', '--ignore-scripts'], {cwd: dir, encoding: 'utf8'});
  const [info] = JSON.parse(out);
  const files = info.files.map((f) => f.path).sort();
  const fonts = files.filter((f) => f.startsWith('fonts/'));
  const other = files.filter((f) => !f.startsWith('fonts/'));
  const extra = other.filter((f) => !METADATA_FILES.includes(f));
  const absent = METADATA_FILES.filter((f) => !other.includes(f));
  if (extra.length) problems.push(`unexpected files in the tarball: ${extra.join(', ')}`);
  if (absent.length) problems.push(`missing from the tarball: ${absent.join(', ')}`);
  if (!metadata && fonts.length !== PAGES) problems.push(`the tarball holds ${fonts.length} font files, not ${PAGES}`);
  const mb = info.size / 1e6;
  if (!metadata && (mb < 35 || mb > 60)) problems.push(`tarball of ${mb.toFixed(1)} MB is outside 35-60 MB`);
  if (problems.length) {
    for (const p of problems) console.error(`[fonts] ${set}: ${p}`);
    fail(`${set}: ${problems.length} packaging problem(s)`);
  }
  log(
    `${set}: ${pkg.name}@${pkg.version} packs ${files.length} files, ${mb.toFixed(1)} MB${metadata ? ' (metadata only)' : ''}`,
  );
};

// ---- drift / download --------------------------------------------------------------------------

const etagMd5 = (etag) => (etag ? etag.replace(/^W\//, '').replaceAll('"', '') : null);

const drift = async (set, {json}) => {
  const manifest = readManifest(set);
  const entries = Object.entries(manifest.files);
  const changed = [];
  const errors = [];
  await runPool(entries, 6, async ([page, entry]) => {
    const url = cdnUrlOf(set, entry.file);
    try {
      const res = await fetch(url, {method: 'HEAD'});
      if (!res.ok) {
        errors.push(`page ${page}: HTTP ${res.status} for ${url}`);
        return;
      }
      const md5 = etagMd5(res.headers.get('etag'));
      const length = Number(res.headers.get('content-length'));
      // A strong ETag on these files is the file's MD5; anything else is checked by downloading.
      if (md5 === entry.md5) return;
      const body = Buffer.from(await (await fetchWithRetry(url, {accept: '*/*'})).arrayBuffer());
      if (hash('sha256', body) !== entry.sha256) changed.push({page: Number(page), url, bytes: body.length || length});
    } catch (e) {
      errors.push(`page ${page}: ${e.message}`);
    }
  });
  changed.sort((a, b) => a.page - b.page);
  if (json) console.log(JSON.stringify({set, snapshot: manifest.snapshot, changed, errors}, null, 2));
  else {
    for (const e of errors) console.error(`[fonts] ${set}: ${e}`);
    log(
      `${set}: ${changed.length} page(s) differ from snapshot ${manifest.snapshot}${changed.length ? `: ${changed.map((c) => c.page).join(', ')}` : ''}`,
    );
  }
  if (errors.length) process.exit(2);
  if (changed.length) process.exit(1);
};

const download = async (set, {out, pages}) => {
  if (!out) fail('download needs --out <dir>');
  fs.mkdirSync(out, {recursive: true});
  const manifest = fs.existsSync(manifestPath(set)) ? readManifest(set) : null;
  const list = parsePageList(pages ?? 'all', PAGES);
  await runPool(list, 4, async (page) => {
    // The format QUL publishes: the snapshot's, else woff2 with woff as the fallback.
    const known = manifest?.files[page]?.file;
    const formats = known ? [path.extname(known).slice(1)] : ['woff2', 'woff'];
    for (const format of formats) {
      const url = QPC_V4.fontUrl(set, page, format);
      try {
        const bytes = Buffer.from(await (await fetchWithRetry(url, {accept: '*/*'})).arrayBuffer());
        if (detectFontMagic(bytes) !== format) throw new Error(`${url} is not a ${format} file`);
        fs.writeFileSync(path.join(out, `p${page}.${format}`), bytes);
        return;
      } catch (e) {
        if (format === formats.at(-1)) throw e;
      }
    }
  });
  log(`${set}: downloaded ${list.length} page(s) into ${out}`);
};

// ---- CLI ---------------------------------------------------------------------------------------

const flag = (args, name) => {
  const i = args.indexOf(name);
  return i >= 0 ? (args[i + 1] ?? true) : undefined;
};

const main = async () => {
  const [command, target, ...rest] = process.argv.slice(2);
  if (!command || command === 'help' || command === '--help') {
    console.log(
      fs
        .readFileSync(new URL(import.meta.url), 'utf8')
        .split('\n')
        .filter((l) => l.startsWith('//'))
        .map((l) => l.slice(3))
        .join('\n'),
    );
    return;
  }
  if (!target)
    fail(
      `${command} needs a font set (${SETS.join(', ')}${['snapshot', 'download', 'generate'].includes(command) ? '' : ', or all'})`,
    );
  switch (command) {
    case 'snapshot':
      return snapshot(
        assertSet(target),
        flag(rest, '--from'),
        flag(rest, '--date') ?? new Date().toISOString().slice(0, 10),
      );
    case 'generate':
      for (const set of setsOf(target)) generate(set);
      return;
    case 'fill':
      for (const set of setsOf(target)) await fill(set, {from: flag(rest, '--from'), cdn: rest.includes('--cdn')});
      return;
    case 'verify':
      for (const set of setsOf(target)) verify(set);
      return;
    case 'check':
      for (const set of setsOf(target)) check(set, {metadata: rest.includes('--metadata')});
      return;
    case 'drift':
      for (const set of setsOf(target)) await drift(set, {json: rest.includes('--json')});
      return;
    case 'download':
      return download(assertSet(target), {out: flag(rest, '--out'), pages: flag(rest, '--pages')});
    default:
      fail(`unknown command ${JSON.stringify(command)}; run \`fonts help\``);
  }
};

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => fail(e.stack ?? String(e)));
}
